### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by de2apandi** [bangnopal/joox-downloader#1]
bang tolong di update scriptnya

saya dapet error kayak gini

Notice: Undefined property: stdClass::$mp3Url in /storage/ssd5/970/17362970/public_html/mp3.php on line 15

Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd5/970/17362970/public_html/mp3.php:15) in /storage/ssd5/970/17362970/public_html/mp3.php on line 21

Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd5/970/17362970/public_html/mp3.php:15) in /storage/ssd5/970/17362970/public_html/mp3.php on line 22

Warning: readfile(): Filename cannot be empty in /storage/ssd5/970/17362970/public_html/mp3.php on line 23

**Comment by bangnopal** [comment]
Punya saya normal kok gan, coba cek https://joox.rajinulis.my.id

**Comment by de2apandi** [comment]
iya ya , saya tes deploy di freehosting, error kayak gitu

**Comment by bangnopal** [comment]
Coba cek versi php nya, saya menyarankan versi php 7 keatas. Mungkin juga ada beberapa fitur di freehosting yg dinonaktifkan. Klo mau coba host script ini secara gratis, pakai heroku.com aja

**Comment by bangnopal** [comment]
Issue tidak dilanjutkan, saya anggap ini sudah fix ya. Terimakasih sudah membuat laporan ^_^
